artifacts_root: artifacts



data_ingestion: #always make sure for the indentations otherwise it will give an error.
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ravina029/datasets/raw/main/WineQT.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion










